security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      entry_point: form_login
      form_login:
        login_path: login
        check_path: login
        username_parameter: _username
        password_parameter: _password
        enable_csrf: false
        default_target_path: admin_pricing_index
        always_use_default_target_path: true
      logout:
        path: logout
        target: home

  access_control:
    - { path: ^/login$,  roles: PUBLIC_ACCESS }
    - { path: ^/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/admin,  roles: ROLE_ADMIN }
    - { path: ^/,       roles: PUBLIC_ACCESS }
